FROM node:22-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm ci && npm cache clean --force

COPY . .

CMD ["npm", "start"]

EXPOSE 3000