FROM node:22-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
# RUN npm i react-redux @heroicons/react @reduxjs/toolkit
RUN npm ci --silent

COPY . .



EXPOSE 3000

CMD ["npm", "start"]